# Generated by Django 3.1.3 on 2020-11-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LISP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='created_at',
        ),
        migrations.AddField(
            model_name='rating',
            name='washroom_type',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unisex'), ('H', 'Handicap')], default='U', max_length=8),
        ),
    ]
