# Generated by Django 3.1.3 on 2020-11-08 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LISP', '0002_auto_20201107_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='rating',
        ),
        migrations.AddField(
            model_name='rating',
            name='cleanliness',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rating',
            name='num_of_ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rating',
            name='overall',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rating',
            name='smell',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='LISP.coordinate'),
        ),
    ]
