# Generated by Django 3.1.3 on 2020-11-08 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LISP', '0003_auto_20201107_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='primaryind',
            field=models.IntegerField(default=-1),
        ),
    ]
