# Generated by Django 3.1.3 on 2021-01-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LISP', '0004_rating_primaryind'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='distance',
            field=models.IntegerField(default=0),
        ),
    ]
