# Generated by Django 3.1.3 on 2021-01-06 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LISP', '0005_rating_distance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='distance',
        ),
    ]
