# Generated by Django 3.1.3 on 2021-01-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LISP', '0007_rating_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='distance',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
    ]
