# Generated by Django 3.1.3 on 2021-01-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LISP', '0008_auto_20210106_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='address',
            field=models.TextField(default=''),
        ),
    ]
